server:
  port: 8010

spring:
  application:
    name: microservice-simple-concusmer-movie
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:123@localhost:8761/eureka/
  instance:
    prefer-ip-address: true

# ribbon configure
microservice-provider-simple-user:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule